# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_format',
            field=models.CharField(max_length=10),
        ),
    ]
