# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0004_auto_20170411_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='upload',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
