# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0005_auto_20170411_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='firstname',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='user_pic',
            field=models.CharField(default=0, max_length=2050),
            preserve_default=False,
        ),
    ]
