# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0007_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 17, 17, 55, 41, 738283, tzinfo=utc)),
        ),
    ]
