# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0009_auto_20170417_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 17, 18, 4, 46, 782648, tzinfo=utc)),
        ),
    ]
