# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0010_auto_20170417_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
