# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0011_auto_20170417_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='description',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
