# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0012_liked_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='like_id',
            field=models.IntegerField(default=1),
        ),
    ]
