# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gag', '0013_auto_20170418_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='like_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='like',
            field=models.IntegerField(default=1),
        ),
    ]
